### ISSUE TITLE
Failed to connect on a connection using ath9k in Debian Stretch

### ISSUE THREAD

**Issue by leandrocunha526** [qca/open-ath9k-htc-firmware#133]
Bug report in Debian Bug Tracker https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=870159
This problem is old and needs a solution on the part of the debian developers and the firmware developers. I do not know the cause of this incident.

**Comment by olerem** [comment]
Most probably it is same issue https://github.com/qca/open-ath9k-htc-firmware/issues/132

**Comment by leandrocunha526** [comment]
Problem solved 
https://bugs.launchpad.net/ubuntu/+source/wpa/+bug/1867908
