### ISSUE TITLE
Disable rate control

### ISSUE THREAD

**Issue by stathopou** [qca/open-ath9k-htc-firmware#60]
Greetings,

In order to do some measurements, I need to disable rate control in ath9k_htc. Having disabled minstrel and PID rate control algorithms I expected that no rate control would be applied. However, I recently discovered that rate control in ath9k_htc goes back to the firmware. So, it there any way to disable rate control in the firmware? If so, is there a patch that I can apply to the source code? Any help is appreciated. 

Thank in advance,
Nikos Stathopoulos

**Comment by sreekrishnapandi** [comment]
Hi,
Did you find any solution to this problem? I am facing the same issue. I want to set manual rates on the ath_9k_htc device.

**Comment by EduardoFF** [comment]
Hi, I'm also trying to disable the rate control. Any news regarding this issue?

**Comment by sreekrishnapandi** [comment]
*Ugly ugly fix* 
https://github.com/rpp0/open-ath9k-htc-firmware

This worked for me. 
![image](https://cloud.githubusercontent.com/assets/8693566/11397663/6216f9e2-937b-11e5-825f-d3d70081b1d1.png)

**Comment by EduardoFF** [comment]
Ugly fix but it works. Thanks a lot.

**Comment by erikarn** [comment]
Hi,

I'd like to merge this stuff into the main firmware branch. Is someone able/willing to tidy up the fixed rate definition stuff a bit? (eg hardcoding short-GI.)

**Comment by psyborg55** [comment]
why do they listed as a feature at rpp0:

Dynamically configure a fixed data rate.

if we can only hardcode a single rate?

another thing, 6 and 9 Mbps are set to false in both github repos, is there some problem when using those rates?

**Comment by cagrazia** [comment]
Hi all,

I'm interested in this (old) topic. The solution of @sreekrishnapandi seems to be tailored for old kernels, is anyone here aware of some new patch/firmware to disable rate control on ath9k_htc??

Thank you all so much

**Comment by erikarn** [comment]
Hi,

I think we have to add rate control WMI commands to the firmware API.



-adrian
