### ISSUE TITLE
Time to push 1.4

### ISSUE THREAD

**Issue by olerem** [qca/open-ath9k-htc-firmware#65]
Hi Adrian,
it is good time to make 1.4 release. It works for me, and looks like it fix some bugs for other people.

**Comment by chenyow** [comment]
Agreed, it's time.

**Comment by f-andrey** [comment]
I'm testing build project in the FreeBSD
env
FreeBSD des.local 11.0-CURRENT FreeBSD 11.0-CURRENT #5 r276782M: Wed Jan  7 21:59:17 MSK 2015     root@des.local:/usr/obj/usr/src/sys/GENERIC  amd64
wget/gcc/gmake

for build need set env "CC=gcc48"

Unfortunately, I have nothing to test the efficiency of the resulting firmware, they are available at
http://bsdnir.info/files/forgithub/htc_7010.fw
http://bsdnir.info/files/forgithub/htc_9271.fw

**Comment by olerem** [comment]
this issue can be closed. It's probably time to push 1.5 ;)
