### ISSUE TITLE
ath9k/ath9k_htc high power possible or marketing trick only?

### ISSUE THREAD

**Issue by psyborg55** [qca/open-ath9k-htc-firmware#89]
Hi

I've ran across many websites with several different ways of getting devices based on ath9k and ath9k_htc driver running at high power.

I understand not all of the cards can support powers of 500 or more mW but at least one I got according to windows driver readings can output 1000 mW.

The problem is whatever I do, driver simply won't make the hardware transmit at higher power.

For example: TL-WN722N adapter is rated as 27dBm output for FCC countries, but setting any value over 18dBm makes no difference on remote AP. I've tried several methods I found online and none worked including one at http://yo3iiu.ro/blog/?p=1301 where the guy obviously managed to get higher output power.

That's why I'm puzzled how come this not work, is it newer firmware/driver problem, newer kernel problem or something else? Is there more of the driver properties needed to modify in order to get higher output on recent drivers/kernels?

**Comment by erikarn** [comment]
hiya,

can someone provide a dump from debugfs ath9k with the current eeprom
contents? :) That way it's parsed.

Thanks!



-adrian
